import { useState } from 'react';
import PropTypes from 'prop-types';
import { COVER_OPTIONS } from '../constants/coverOptions';
import { PC_STORES, PLATFORMS, STATUSES } from '../constants/gameOptions';

const GameForm = ({ form, isEditing, isSaving, onChange, onSubmit, onCancel }) => {
    const [coverMode, setCoverMode] = useState(form.imageUrl?.startsWith('/') ? 'library' : 'url');
    const [coverSearch, setCoverSearch] = useState('');
    const [errors, setErrors] = useState({});
    const [imageError, setImageError] = useState(false);
    const update = (changes) => {
        onChange((current) => ({ ...current, ...changes }));
        setErrors((current) => ({ ...current, ...Object.fromEntries(Object.keys(changes).map((key) => [key, ''])) }));
    };
    const completed = form.status === 'Completado';
    const visibleCovers = COVER_OPTIONS.filter((cover) => cover.label.toLowerCase().includes(coverSearch.toLowerCase()));

    const validateAndSubmit = (event) => {
        event.preventDefault();
        const nextErrors = {};
        if (!form.title.trim()) nextErrors.title = 'Escribe el nombre del juego.';
        if (form.rating !== '' && (Number(form.rating) < 0 || Number(form.rating) > 10)) nextErrors.rating = 'La puntuación debe estar entre 0 y 10.';
        if (form.imageUrl && !form.imageUrl.startsWith('/') && !/^https?:\/\//i.test(form.imageUrl)) nextErrors.imageUrl = 'Usa una URL http(s) o una portada de la biblioteca.';
        setErrors(nextErrors);
        if (!Object.keys(nextErrors).length) onSubmit(event);
    };

    return <form onSubmit={validateAndSubmit} className="bg-gray-900" noValidate>
        <div className="grid gap-0 lg:grid-cols-[280px_1fr]">
            <aside className="border-b border-gray-800 bg-gray-950/70 p-5 lg:border-b-0 lg:border-r">
                <SectionKicker>Portada</SectionKicker>
                <div className="relative mx-auto mt-4 aspect-[3/4] max-w-[210px] overflow-hidden rounded-xl border border-gray-700 bg-gray-800 shadow-xl">
                    <img src={imageError || !form.imageUrl ? '/GameTracker.ico' : form.imageUrl} alt={form.imageUrl ? 'Previsualización de la portada' : 'Sin portada seleccionada'} className="h-full w-full object-cover" onError={() => setImageError(true)} />
                    {form.imageUrl && <button type="button" onClick={() => { update({ imageUrl: '' }); setImageError(false); }} className="absolute right-2 top-2 rounded-lg bg-black/70 px-2 py-1 text-xs text-white">Quitar</button>}
                </div>
                <div className="mt-5 grid grid-cols-2 gap-1 rounded-lg bg-gray-800 p-1 text-xs"><button type="button" onClick={() => setCoverMode('library')} className={`rounded-md px-2 py-2 ${coverMode === 'library' ? 'bg-blue-600 text-white' : 'text-gray-400'}`}>Biblioteca</button><button type="button" onClick={() => setCoverMode('url')} className={`rounded-md px-2 py-2 ${coverMode === 'url' ? 'bg-blue-600 text-white' : 'text-gray-400'}`}>URL externa</button></div>
                {coverMode === 'url' ? <div className="mt-3"><label htmlFor="image-url" className="text-xs text-gray-400">URL o ruta personalizada</label><input id="image-url" type="text" value={form.imageUrl} onChange={(event) => { setImageError(false); update({ imageUrl: event.target.value }); }} placeholder="/SPIDER-PS5.jpg" className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-800 p-2 text-sm text-white" />{errors.imageUrl && <ErrorMessage>{errors.imageUrl}</ErrorMessage>}</div> : <div className="mt-3"><label htmlFor="cover-search" className="sr-only">Buscar portada</label><input id="cover-search" type="search" value={coverSearch} onChange={(event) => setCoverSearch(event.target.value)} placeholder="Buscar portada..." className="w-full rounded-lg border border-gray-700 bg-gray-800 p-2 text-sm text-white" /><div className="mt-2 grid max-h-48 grid-cols-3 gap-2 overflow-y-auto pr-1">{visibleCovers.map((cover) => <button type="button" key={cover.file} onClick={() => { setImageError(false); update({ imageUrl: cover.src }); }} className={`overflow-hidden rounded-lg border-2 ${form.imageUrl === cover.src ? 'border-blue-400' : 'border-transparent'}`} title={cover.label}><img src={cover.src} alt={cover.label} loading="lazy" className="aspect-[3/4] w-full object-cover" /></button>)}</div></div>}
            </aside>
            <div>
                <section className="border-b border-gray-800 p-5 sm:p-7"><SectionKicker>Información principal</SectionKicker><div className="mt-4 space-y-4"><Field id="game-title" label="Nombre del videojuego" value={form.title} placeholder="Ej. Marvel's Spider-Man 2" error={errors.title} required onChange={(value) => update({ title: value })} /><label htmlFor="description" className="block text-sm font-medium text-gray-300">Descripción <span className="font-normal text-gray-500">(opcional)</span><textarea id="description" value={form.description} onChange={(event) => update({ description: event.target.value })} maxLength="2000" placeholder="Notas, opinión o contexto personal..." className="mt-1 min-h-24 w-full resize-y rounded-lg border border-gray-700 bg-gray-800 p-3 text-white" /><span className="mt-1 block text-right text-xs text-gray-500">{form.description.length}/2000</span></label></div></section>
                <section className="border-b border-gray-800 p-5 sm:p-7"><SectionKicker>Clasificación</SectionKicker><div className="mt-4 space-y-5"><div><p className="mb-2 text-sm font-medium text-gray-300">Estado</p><div className="grid gap-2 sm:grid-cols-3">{STATUSES.map((status) => <button type="button" key={status} onClick={() => update({ status, replayable: status === 'Completado' ? form.replayable : false, platinated: status === 'Completado' ? form.platinated : false })} aria-pressed={form.status === status} className={`rounded-xl border p-3 text-left ${form.status === status ? 'border-blue-400 bg-blue-500/15 text-white' : 'border-gray-700 bg-gray-800 text-gray-400'}`}><span className="block text-sm font-bold">{status === 'Backlog' ? '📚' : status === 'Jugando' ? '🎮' : '✅'} {status}</span><span className="mt-1 block text-xs text-gray-500">{status === 'Backlog' ? 'Pendiente de jugar' : status === 'Jugando' ? 'Actualmente en progreso' : 'Ya terminado'}</span></button>)}</div></div><div><p className="mb-2 text-sm font-medium text-gray-300">Plataforma</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{PLATFORMS.map((platform) => <button type="button" key={platform} onClick={() => update({ platform, pcStore: platform === 'PC' ? form.pcStore : '' })} aria-pressed={form.platform === platform} className={`rounded-lg border px-3 py-2 text-sm ${form.platform === platform ? 'border-blue-400 bg-blue-500/15 text-blue-200' : 'border-gray-700 bg-gray-800 text-gray-400'}`}>{platform}</button>)}</div></div>{form.platform === 'PC' && <Select id="pc-store" label="Tienda de PC" value={form.pcStore} options={PC_STORES} empty="Sin especificar" onChange={(value) => update({ pcStore: value })} />}<label className={`flex cursor-pointer items-start gap-3 rounded-xl border p-4 ${form.isOnline ? 'border-cyan-400/50 bg-cyan-400/10' : 'border-gray-700 bg-gray-800'}`}><input type="checkbox" checked={form.isOnline} onChange={(event) => update({ isOnline: event.target.checked })} className="mt-1 h-4 w-4 accent-cyan-500" /><span><span className="block text-sm font-bold text-gray-200">🌐 Juego online</span><span className="mt-1 block text-xs leading-5 text-gray-500">No contará en el progreso de juegos completables ni en la tasa de completado.</span></span></label></div></section>
                <section className="p-5 sm:p-7"><SectionKicker>Tu seguimiento</SectionKicker><div className="mt-4 grid gap-5 sm:grid-cols-2"><div><div className="flex items-end justify-between"><label htmlFor="rating" className="text-sm font-medium text-gray-300">Puntuación</label><span className="text-lg font-black text-yellow-300">{form.rating === '' ? 'Sin puntuar' : `${Number(form.rating).toFixed(1)} / 10`}</span></div><input id="rating" type="range" min="0" max="10" step="0.1" value={form.rating === '' ? 0 : form.rating} onChange={(event) => update({ rating: event.target.value })} className="mt-4 w-full accent-yellow-400" aria-label="Puntuación de 0 a 10" />{errors.rating && <ErrorMessage>{errors.rating}</ErrorMessage>}</div><label htmlFor="target-year" className="block text-sm font-medium text-gray-300">{completed ? 'Año de completado' : 'Año objetivo'}<select id="target-year" value={form.targetYear} onChange={(event) => update({ targetYear: event.target.value })} className="mt-2 w-full rounded-lg border border-gray-700 bg-gray-800 p-3 text-white"><option value="">Sin especificar</option>{years().map((year) => <option key={year} value={year}>{year}</option>)}</select></label></div>{completed && <div className="grid gap-3 sm:grid-cols-2"><Check label="Lo volvería a jugar" hint="Vale la pena repetirlo" checked={form.replayable} onChange={(value) => update({ replayable: value })} /><Check label="Platinado / 100%" hint="Todos los logros conseguidos" checked={form.platinated} onChange={(value) => update({ platinated: value })} /></div>}</section>
            </div>
        </div>
        <footer className="sticky bottom-0 flex items-center justify-between gap-3 border-t border-gray-700 bg-gray-900/95 p-4 backdrop-blur sm:px-7"><p className="hidden text-xs text-gray-500 sm:block">{isEditing ? 'Los cambios se aplicarán al guardar.' : 'Puedes completar estos datos más adelante.'}</p><div className="ml-auto flex gap-3"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-3 text-sm font-semibold text-gray-300 hover:bg-gray-800">Cancelar</button><button type="submit" disabled={isSaving} className="min-w-36 rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-500 disabled:opacity-50">{isSaving ? 'Guardando...' : isEditing ? 'Guardar cambios' : 'Añadir juego'}</button></div></footer>
    </form>;
};

const years = () => Array.from({ length: 21 }, (_, index) => new Date().getFullYear() - 10 + index);
const SectionKicker = ({ children }) => <p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">{children}</p>;
const ErrorMessage = ({ children }) => <p className="mt-1 text-xs text-red-300" role="alert">{children}</p>;
const Field = ({ id, label, value, placeholder, error, required, onChange }) => <label htmlFor={id} className="block text-sm font-medium text-gray-300">{label}{required && <span className="ml-1 text-blue-400">*</span>}<input id={id} type="text" value={value} placeholder={placeholder} required={required} onChange={(event) => onChange(event.target.value)} className={`mt-1 w-full rounded-lg border bg-gray-800 p-3 text-white ${error ? 'border-red-400' : 'border-gray-700'}`} />{error && <ErrorMessage>{error}</ErrorMessage>}</label>;
const Select = ({ id, label, value, options, empty, onChange }) => <label htmlFor={id} className="block text-sm font-medium text-gray-300">{label}<select id={id} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-700 bg-gray-800 p-3 text-white"><option value="">{empty}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>;
const Check = ({ label, hint, checked, onChange }) => <label className={`flex cursor-pointer items-start gap-3 rounded-xl border p-4 ${checked ? 'border-blue-400 bg-blue-500/10' : 'border-gray-700 bg-gray-800'}`}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-4 w-4 accent-blue-500" /><span><span className="block text-sm font-semibold text-gray-200">{label}</span><span className="mt-1 block text-xs text-gray-500">{hint}</span></span></label>;

SectionKicker.propTypes = { children: PropTypes.node.isRequired };
ErrorMessage.propTypes = { children: PropTypes.node.isRequired };
Field.propTypes = { id: PropTypes.string.isRequired, label: PropTypes.string.isRequired, value: PropTypes.string.isRequired, placeholder: PropTypes.string, error: PropTypes.string, required: PropTypes.bool, onChange: PropTypes.func.isRequired };
Select.propTypes = { id: PropTypes.string.isRequired, label: PropTypes.string.isRequired, value: PropTypes.string.isRequired, options: PropTypes.arrayOf(PropTypes.string).isRequired, empty: PropTypes.string.isRequired, onChange: PropTypes.func.isRequired };
Check.propTypes = { label: PropTypes.string.isRequired, hint: PropTypes.string.isRequired, checked: PropTypes.bool.isRequired, onChange: PropTypes.func.isRequired };
GameForm.propTypes = { form: PropTypes.object.isRequired, isEditing: PropTypes.bool.isRequired, isSaving: PropTypes.bool.isRequired, onChange: PropTypes.func.isRequired, onSubmit: PropTypes.func.isRequired, onCancel: PropTypes.func.isRequired };

export default GameForm;
